/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#ifndef _HW_H_RPCGEN
#define _HW_H_RPCGEN

#include <rpc/rpc.h>


#ifdef __cplusplus
extern "C" {
#endif


struct rpc_args_t {
	uint64_t *src_add;
	int len;
	char *dest_add;
	uint32_t qp_num;
};
typedef struct rpc_args_t rpc_args_t;

#define HELLO_WOLRD_PROG 0x30000824
#define HELLO_WORLD_VERS 1

#if defined(__STDC__) || defined(__cplusplus)
#define HW 1
extern  char ** hw_1(rpc_args_t *, CLIENT *);
extern  char ** hw_1_svc(rpc_args_t *, struct svc_req *);
extern int hello_wolrd_prog_1_freeresult (SVCXPRT *, xdrproc_t, caddr_t);

#else /* K&R C */
#define HW 1
extern  char ** hw_1();
extern  char ** hw_1_svc();
extern int hello_wolrd_prog_1_freeresult ();
#endif /* K&R C */

#define RDMA_CONNECT_PROG 0x30000825
#define RDMA_CONNECT_VERS 1

#if defined(__STDC__) || defined(__cplusplus)
#define RDMAC 1
extern  char ** rdmac_1(void *, CLIENT *);
extern  char ** rdmac_1_svc(void *, struct svc_req *);
extern int rdma_connect_prog_1_freeresult (SVCXPRT *, xdrproc_t, caddr_t);

#else /* K&R C */
#define RDMAC 1
extern  char ** rdmac_1();
extern  char ** rdmac_1_svc();
extern int rdma_connect_prog_1_freeresult ();
#endif /* K&R C */

/* the xdr functions */

#if defined(__STDC__) || defined(__cplusplus)
extern  bool_t xdr_rpc_args_t (XDR *, rpc_args_t*);

#else /* K&R C */
extern bool_t xdr_rpc_args_t ();

#endif /* K&R C */

#ifdef __cplusplus
}
#endif

#endif /* !_HW_H_RPCGEN */
