/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#include "hw.h"

bool_t
xdr_rpc_args_t (XDR *xdrs, rpc_args_t *objp)
{
	register int32_t *buf;

	 if (!xdr_pointer (xdrs, (char **)&objp->src_add, sizeof (uint64_t), (xdrproc_t) xdr_uint64_t))
		 return FALSE;
	 if (!xdr_int (xdrs, &objp->len))
		 return FALSE;
	 if (!xdr_pointer (xdrs, (char **)&objp->dest_add, sizeof (uint64_t), (xdrproc_t) xdr_uint64_t))
		 return FALSE;
	 if (!xdr_uint32_t (xdrs, &objp->qp_num))
		 return FALSE;
	return TRUE;
}
